<?php /** @var $block Success*/

use Cetelem\Payment\Block\Success; ?>
<?php $order = $block->getOrderId();?>
<?php if($block->getOrderStatus() == 'canceled'):?>
	<h1><?= __("We're very sorry!")?></h1>
	<?php else : ?>
	<h1><?= __("Thank you for your purchase!")?></h1>
<?php endif;?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
			<?php if(in_array($block->getOrderStatus(), ['pending_cetelem','pending_encuotas'])):?>
                <img src="<?= $block->escapeHtml($block->getLogo($block->getOrderPaymentMethod()))?>" style="width:150px;">
				<p><?= $block->escapeHtml(__('Your order %1 is pending approval', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
            <?php else:?>
				<p><?= $block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
				<p><?= /* @escapeNotVerified */ __("We'll email you an order confirmation with details.") ?></p>
			<?php endif; ?>
        <?php endif;?>
    <?php endif;?>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
